---
---
# tasks file for db
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- include: install_mongo.yml
- name: Show if the  install_mongo.yml has been run
  debug:
    msg: "install_mongo run has been run in {{ env }} environment!!!"

- include: config_mongo.yml
- name: Show if config_mongo.yml has been run
  debug: msg="config_mongo run has been run in {{ env }} environment!!!"

# tasks file for db
#- name: Show info about the env this host belongs to
#  debug: msg="This host is in {{ env }} environment!!!"

#- include: install_mongo.yml
#- name: Show if install_mongo.yml has been run
#  debug: 
#    msg: "install_mongo run has been run in {{ env }} environment!!!"

#- include: config_mongo.yml
#- name: Show if config_mongo.yml has been run
#  debug: msg="config_mongo run has been run in {{ env }} environment!!!"
