---
- name: Deploy application
  hosts: app
  become: true
  vars:
    deploy_user: appuser

  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith # <--point the necessary branch
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: "/home/{{ deploy_user }}/reddit"  # <-- the working directory where script will be run

  handlers:
    - name: reload puma
      systemd: name=puma state=restarted

